// ============================================================
//  FINALES y pantallas de cierre
// ============================================================

window.FINALES = {
  // Cuando la sospecha llega al 100%
  detenido: {
    inicio: 'd1',
    nodos: {
      d1: { escena: 'oficina', quien: 'brandt', texto: 'Vogt. Acompáñeme. No, deje el abrigo. No lo va a necesitar.', siguiente: 'd2' },
      d2: { quien: 'guardia', texto: 'Ciudadano 44-190-V. Índice de Pureza recalculado: 0. Queda usted a disposición de la Guardia Negra.', siguiente: 'd3' },
      d3: { escena: 'negro', texto: 'Nadie en la Sección 14 levanta la vista de su mesa. Nadie mira las caras.', siguiente: 'd4' },
      d4: { texto: 'Al día siguiente, otro archivero ocupa la silla de Elías Vogt. Revisa su primer expediente. Es el de Elías.' }
    }
  },

  // Pantalla al terminar el prototipo (Día 1 + Noche 1)
  prototipo: {
    titulo: 'FIN DEL DÍA 5',
    subtitulo: 'Quedan dos noches para el Día del Sol.',
    lineas: [
      { si: 'brandtPurgado', texto: 'El Supervisor Brandt ha sido purgado. La Inspectora Hel ocupa su mesa.' },
      { si: 'recluta_brandt', texto: 'Konrad Brandt se ha unido a los Insomnes. El domingo tendrá la llave de una puerta.' },
      { si: ['brandtSalvado', '!recluta_brandt'], texto: 'Salvaste a Brandt de la purga. No sabes qué hará con esa deuda.' },
      { si: 'denuncioBrandt', texto: 'Diste el nombre de Brandt a la Inspectora.' },
      { si: 'denuncioLeo', texto: 'Diste el nombre de Leo Sanz, el chico que miraba las caras.' },
      { si: 'denunciaFalsa', texto: 'Le diste a la Inspectora el nombre de un muerto. Ruth te enseñó bien.' },
      { si: 'klausRescatado', texto: 'Klaus Ernst bajó del tren a oscuras. No sabe a quién le debe qué.' },
      { si: ['klausReubicado', '!klausRescatado'], texto: 'Klaus Ernst va en un tren hacia el Este. Por tu denuncia.' },
      { si: 'hijoDeLaVoz', texto: 'Los líderes de las células saben que eres el hijo de la Voz de Madrid.' },
      { si: 'celulaFerroviarios', texto: 'Los Ferroviarios del Distrito 11 se unirán el domingo.' },
      { si: 'celulaTejedoras', texto: 'Las Tejedoras del Distrito 4 se unirán el domingo.' },
      { si: 'celulaAnselmo', texto: 'La gente de Anselmo, en el Distrito 9, se unirá el domingo.' },
      { si: 'planosAguja', texto: 'Tenéis los planos de La Aguja. El núcleo de ODÍN está en el nivel -4.' },
      { si: 'eclipseSincronizado', texto: 'Veinte relojes marcan la misma hora: el minuto empieza a las 21:00:00.' },
      { si: 'vozVuelve', texto: 'La Voz de Madrid ha vuelto a sonar después de nueve años.' },
      { si: 'confiaRelojero', texto: 'Le prometiste al Relojero que confiarías en él, pase lo que pase.' },
      { si: 'dudaRelojero', texto: 'No quisiste prometerle al Relojero tu confianza.' },
      { si: 'baile', texto: 'Mara y Elías bailaron mal, entre cajas de fusiles.' },
      { si: 'octavillaMadre', texto: 'Llevas una octavilla con la letra de tu madre: «Sigue mirando».' },
      { si: 'nombreDicho', texto: 'Elías Aranda. Lo ha dicho en voz alta por primera vez en treinta y dos años.' },
      { si: 'nombreGuardado', texto: 'Elías Aranda. Lo lleva doblado en el bolsillo, junto al corazón.' },
      { si: '!nombreReal', texto: 'Elías sigue sin saber su nombre. El Proyecto Semilla arderá el domingo.' },
      { si: 'nombreReal', texto: 'Su madre era Julia Aranda, la Voz de Madrid. «¿Recuerdas Madrid?» era su frase.' },
      { si: 'relojeroConfeso', texto: 'El Relojero lo encontró en 2008 y lo escondió en 2032. Queda una última verdad. «La peor.»' },
      { si: 'ruthCaida', texto: 'Ruth no volvió del Archivo Central. Dejó la caja en el buzón: «Para el niño que miraba».' },
      { si: 'ruthConocioMadre', texto: 'Ruth imprimía las octavillas de Julia Aranda.' },
      { si: 'capturado_tomas', texto: 'Chispa ha caído en manos de la Guardia Negra.' },
      { si: 'denuncioInocente', texto: 'Denunciaste a Klaus Ernst, un inocente, para limpiar tu ficha.' },
      { si: 'fichaLimpia', texto: 'Tu historial en la Dirección de Seguridad ha sido «corregido».' },
      { si: 'brandtLoSabe', texto: 'El número de tu pase está en un papel camino de la mesa de Brandt.' },
      { si: 'auroraExpulsada', texto: 'Echasteis a Aurora Blanco antes de que tendiera su emboscada.' },
      { si: 'auroraEngañada', texto: 'Aurora cree que el Proyecto Semilla está en el Archivo del Distrito 11.' },
      { si: 'promesaLunes', texto: 'Mara tiene algo que decirle a Elías. El lunes. Tienen que llegar al lunes.' },
      { si: 'nombreMara', texto: 'Mara Solís Ortega, nacida en Lavapiés. Elías lo recordará.' },
      { si: 'armas', texto: 'Doce fusiles de 2029 esperan envueltos en lona.' },
      { si: 'celulasSur', texto: 'Las células del sur se unirán el domingo.' },
      { si: 'redadaEvitada', texto: 'Elías llegó a tiempo. La redada encontró un sótano vacío.' },
      { si: 'redadaSufrida', texto: 'La redada de la Calle del Reloj costó cara. Nico Barros abrió la puerta.' },
      { si: 'capturado_julian', texto: 'Julián Mora sujetó la puerta. Se lo llevaron.' },
      { si: 'capturado_greta', texto: 'Greta Lang está en manos de la Guardia Negra.' },
      { si: 'capturado_irene', texto: 'Irene Castaño está en manos de la Guardia Negra.' },
      { si: 'imprentaPerdida', texto: 'La imprenta de Ruth ya no existe. Le queda la letra M.' },
      { si: 'refugioAnden', texto: 'Los Insomnes viven ahora en el andén abandonado de la vieja estación de Sol.' },
      { si: 'relojeroRescatado', texto: 'El Relojero está libre. Dice que lo sacasteis de donde necesitaba estar.' },
      { si: 'mensajeRelojero', texto: 'Mensaje del Relojero: «El domingo a las 21:00 estaré donde tengo que estar.»' },
      { si: 'relojeroHablo', texto: 'El Relojero conoció a Elías de niño. El resto lo contará el domingo.' },
      { si: 'hansReubicado', texto: 'Hans Keller, mesa 12, va camino del Este. Por memorizar.' },
      { si: 'hansRescatado', texto: 'Hans Keller está libre y lo recuerda todo.' },
      { si: ['memo_semilla', '!semillaConseguida'], texto: 'El Proyecto Semilla está en el Archivo Central, sótano 2, sala 14.' },
      { si: ['semillaDestruccion', '!semillaConseguida'], texto: 'El Proyecto Semilla arderá el domingo.' },
      { si: 'semillaRetrasada', texto: 'Devolviste la orden de quemar el Proyecto Semilla. Ganas tiempo.' },
      { si: ['reconArchivo', '!semillaConseguida'], texto: 'Cuatro minutos sin guardia en la sala 14, a las 03:00.' },
      { si: 'engañoGuardia', texto: 'La Guardia Negra cree que el golpe será en la Ciudadela Helios.' },
      { si: 'llaveODIN', texto: 'Llevas en el bolsillo la llave de mantenimiento de ODÍN.' },
      { si: 'ruthSabe', texto: 'Elías creció en el Hogar número 4. El Relojero trabajó allí.' },
      { si: 'maraMano', texto: 'Mara y Elías se cogieron de la mano en la oscuridad. Ninguno lo ha mencionado.' },
      { si: 'traidorDentro_aurora', texto: 'Aurora Blanco duerme en el refugio. Parece de fiar.' },
      { si: 'traidorExpulsado_aurora', texto: 'Desenmascarasteis a Aurora Blanco.' },
      { si: 'relojeroTrasladado', texto: 'El Relojero está en La Aguja, nivel -4. Donde quizá quería estar.' },
      { si: ['relojeroEnCentro3', '!relojeroRescatado'], texto: 'El Relojero sigue en el Centro de Reeducación 3. Aún se le puede rescatar.' },
      { si: 'sabeVoluntario', texto: 'Sabéis que el Relojero se entregó por su propio pie.' },
      { si: ['pistaHogar', '!ruthSabe'], texto: 'Ruth te ha contado que el Relojero trabajó en un Hogar de Formación.' },
      { si: ['planosCentro3', '!relojeroRescatado'], texto: 'Tenéis los planos del Centro 3.' },
      { si: 'contactoAguja', texto: 'Tenéis un contacto dentro de La Aguja.' },
      { si: 'eclipseDescifrado', texto: 'Protocolo Eclipse: un minuto de oscuridad total el Día del Sol a las 21:00.' },
      { si: 'tomasBuscado', texto: 'Hay una orden de busca y captura contra Chispa. La firmaste tú.' },
      { si: 'traidorUsado_nico', texto: 'Nico Barros sigue creyendo que no sabéis quién es.' },
      { si: ['recluta_irene', '!capturado_irene'], texto: 'Irene Castaño es parte de los Insomnes.' },
      { si: ['recluta_julian', '!capturado_julian'], texto: 'Julián Mora, de la Lista Gris, es parte de los Insomnes.' },
      { si: ['recluta_greta', '!capturado_greta'], texto: 'Greta Lang, ex de la Juventud Solar, es parte de los Insomnes.' },
      { si: 'recluta_klara', texto: 'Klara Dietz, la maestra, se ha unido a los Insomnes.' },
      { si: 'vinculo_mara>=3', texto: 'Mara empieza a esperar a Elías en la puerta.' },
      { si: 'vinculo_tomas>=2', texto: 'Chispa ha empezado a llamar a Elías «hermano», medio en broma.' },
      { si: 'vinculo_ruth>=2', texto: 'Ruth le ha regalado a Elías una postal vieja de la Gran Vía.' },
      { si: 'tomasSalvado', texto: 'Tomás «Chispa» Rey está vivo y es parte de los Insomnes.' },
      { si: 'tomasReubicado', texto: 'Tomás Rey viaja en un vagón de ganado hacia el Este.' },
      { si: ['ireneSalvada', '!recluta_irene'], texto: 'Irene Castaño, la poeta, duerme en una casa fuera de los registros.' },
      { si: 'ireneReubicada', texto: 'Irene Castaño no escribirá más poemas.' },
      { si: 'odinPinchado', texto: 'Los Insomnes escuchan ahora una parte de ODÍN.' },
      { si: 'capturado_tomas', texto: 'Chispa ha caído en manos de la Guardia Negra.' },
      { si: 'aceptoPronto', texto: 'Elías ha dicho «estoy con vosotros». Es la primera vez que dice «nosotros».' },
      { si: 'aceptoDudando', texto: 'Elías aún no sabe si pertenece a algún sitio.' }
    ]
  }
};
